### ISSUE TITLE
read_aatxe_client is pub(crate) rather than pub

### ISSUE THREAD

**Issue by ctm** [8573/irc-bot.rs#52]
I'd like to use `read_aatxe_client` in my bot, but it's only public to the crate. That works for `quote.rs`, because `modules` is currently under `src` rather than under `src/bin`. However, if `modules` is moved to `src/bin`, I think they'll be better examples, since they'll be isolated.

I've gone ahead and made a PR that both makes `read_aatxe_client` public and also moves `modules` to `src/bin`. I'm still new to rust and although I've verified that I haven't introduced any warnings and that the tests still run, if you agree with moving `modules`, I still recommend looking over my work fairly carefully in case I missed something.

If you don't want to move `modules`, that's fine with me, and I'll happily create a smaller PR that just opens up the few places where `pub(crate)` is overly narrow.

**Comment by 8573** [comment]
I agree that the `quote` module shouldn't be using items that aren't fully public, but I don't think the bot modules (`src/modules`) belong in `src/bin`: the latter is for the source code of executables associated with the library whose code constitutes the rest of `src` ([Cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-project-layout)), and the bot modules are not executables but rather part of the library.

I would guess that `read_aatxe_client` is restricted because I wanted not to commit to the underlying IRC implementation (<https://github.com/aatxe/irc>) by making it part of the public API (although it wouldn't be a very high level of commitment, as `irc-bot` is not stable).

I'll push a patch shortly to address this; please let me know if it's not enough.
