### ISSUE TITLE
Minimal bot knows no commands

### ISSUE THREAD

**Issue by phrohdoh** [8573/irc-bot.rs#6]
```rust
extern crate irc_bot as irc;

fn main() {
    irc::run("config.json", |_| {
        irc::core::ErrorReaction::Proceed
    }, &[irc::modules::default(), irc::modules::test()]);
}
```

```json
{
  "owners": ["Phrohdoh"],
  "nickname": "testbot",
  "username": "testbot",
  "realname": "testbot",
  "server": "irc.mozilla.org",
  "channels": ["#rust"],
  "port": 6697,
  "use_ssl": true,
  "options": {}
}
```

This is all I get out of the bot:

```
<testbot> Phrohdoh: Unknown command "help"; apologies. 
<testbot> Phrohdoh: Unknown command "test"; apologies. 
```

**Comment by 8573** [comment]
I reproduced the issue, and was confused, but then I remembered the
cause — the initial, and so far only, release of this library was very
rudimentary, and the provided modules are provided mainly as examples
of how to write modules; the only commands they provide are `join`
(which has the bot join a channel) and `test-line-wrap` (which has the
bot say some lorem ipsum text, to test its line-wrapping mechanism).

The latest version of the library is in the branch `wip/yak-irc/1`.
The provided modules in this version provide more commands, including
a help system.

As the prefix `wip` indicates, this version is a work in progress,
which is why I've not published it to Crates.io — I'm currently
overhauling it for the second or third time.

However, I do try to test the library before pushing, and it mostly
should work just fine; what one should beware with the `wip` version
is that the API is not stable, and I expect I'll overhaul it before
I'm done — but if you're willing, I'll appreciate having a consumer of
the library other than myself from whom to get feedback on how the API
works.

**Comment by 8573** [comment]
I'm c74d on freenode and irc.mozilla.org, and idle in `#c74d` on the
latter network and `#botters-test` on the former, among other
channels. I'd recommend testing the bot in one of those channels over
doing so in `#rust`.

**Comment by 8573** [comment]
> ```
> 2017-07-26 12:42:25 <Phrohdoh> c74d: Hi, how is 'join' the only command available from the default set? There are others in https://github.com/8573/irc-bot.rs/blob/master/src/modules/default.rs and I don't see anything explicitly disabling them.
> 2017-07-26 12:43:06 <Phrohdoh> Oh, it is entirely possible that the crates.io code isn't master -- I didn't consider that.
> ```

The tag `v0.1.0` is what is on Crates.io. The differences between
`v0.1.0` and `master` can be seen here:

<https://github.com/8573/irc-bot.rs/compare/v0.1.0...master>
